### ISSUE TITLE
sock-0.5.5 does not build with ghc-7.4.2?

### ISSUE THREAD

**Issue by juhp** [vincenthz/hs-socks#16]
I tried to cabal install latest pandoc and with ghc-7.4.2 sock-0.5.5 failed to build:

[build.log](https://copr-be.cloud.fedoraproject.org/results/petersen/pandoc/epel-6-x86_64/00332241-pandoc/build.log.gz) ([root.log](https://copr-be.cloud.fedoraproject.org/results/petersen/pandoc/epel-6-x86_64/00332241-pandoc/root.log.gz) shows the base package versions)

```
Network/Socks5/Parse.hs:212:13:
    No instance for (Data.String.IsString ByteString)
      arising from the literal `""'
    Possible fix:
      add an instance declaration for (Data.String.IsString ByteString)
    In the pattern: ""
    In the pattern: (_, "")
    In a case alternative:
        (_, "") -> runParser (getMore >> skipWhile p) B.empty err ok
```

**Comment by phadej** [comment]
http://matrix.hackage.haskell.org/package/socks#GHC-7.4/socks-0.5.5 It doesn't.

```
Dependency base ==4.3.1.0: using base-4.3.1.0
Dependency bytestring ==0.9.1.10: using bytestring-0.9.1.10
Dependency cereal ==0.4.1.1: using cereal-0.4.1.1
Dependency network ==2.6.2.1: using network-2.6.2.1
```
